// reachability — static source audit for shipped-but-unreachable UI.
//
// These checks were originally ad-hoc scratchpad probes re-derived on every audit pass. Committing
// them means `npm test` IS the reachability audit: it either passes, or names exactly what is
// orphaned, unwired or unreachable. No browser needed — this reads the source.
//
// Deliberate exemptions are listed inline with the reason, so a future reader can tell an accepted
// exception from a regression.
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '../..');
const read = f => fs.readFileSync(path.join(ROOT, f), 'utf8');
const SRC_FILES = ['vendor-qrcode', '01-core', '02-data', '03-state', '04-render',
                   '05-combat-build', '06-tabs-init', '07-sync', '08-gm']
  .filter(n => n !== 'vendor-qrcode')
  .map(n => `src/${n}.js`);

module.exports = {
  name: 'reachability',
  async run() {
    const checks = [];
    const html = read('character-tracker.html');
    const src = Object.fromEntries(SRC_FILES.map(f => [f, read(f)]));
    const js = Object.values(src).join('\n');
    const corpus = js + html;
    const ids = new Set([...html.matchAll(/\bid="([A-Za-z0-9_:-]+)"/g)].map(m => m[1]));
    const tabs = new Set([...html.matchAll(/data-tab="([a-z-]+)"/g)].map(m => m[1]));
    const list = a => a.join(', ').slice(0, 120) || 'none';

    // 1. Functions declared but referenced nowhere — dead code the user cannot reach.
    const declared = new Set();
    for (const s of Object.values(src)) {
      for (const m of s.matchAll(/^(?:async )?function ([A-Za-z_$][\w$]*)/gm)) declared.add(m[1]);
    }
    const orphanFns = [...declared].filter(f =>
      (corpus.match(new RegExp('\\b' + f.replace(/\$/g, '\\$') + '\\b', 'g')) || []).length <= 1);
    checks.push({ ok: orphanFns.length === 0, msg: `no orphan functions (${list(orphanFns)})` });

    // 2. Game-content tables defined but never surfaced.
    const consts = [];
    for (const s of Object.values(src)) {
      for (const m of s.matchAll(/^const ([A-Z][A-Z0-9_]{2,})\s*=/gm)) consts.push(m[1]);
    }
    const orphanConsts = consts.filter(c =>
      (corpus.match(new RegExp('\\b' + c + '\\b', 'g')) || []).length <= 1);
    checks.push({ ok: orphanConsts.length === 0, msg: `every content constant is used (${list(orphanConsts)})` });

    // 3. Blocking guards that name a destination but cannot take the player there.
    //    A guard that returns immediately after a bare alert() is a dead end; use requireStep().
    const deadEnds = [];
    for (const [f, s] of Object.entries(src)) {
      for (const m of s.matchAll(/alert\((?:`|')([^`']{0,200})/g)) {
        const text = m[1];
        const after = s.slice(m.index + m[0].length, m.index + m[0].length + 90);
        if (/(tab|first\.|Equip|Set your|Pick a)/.test(text) && /\breturn;/.test(after)) {
          deadEnds.push(path.basename(f) + ': ' + text.slice(0, 44));
        }
      }
    }
    checks.push({ ok: deadEnds.length === 0, msg: `no blocking guard without a jump (${list(deadEnds)})` });

    // 4. requireStep() jump targets must resolve to a real tab and a real card.
    const badJumps = [];
    for (const m of js.matchAll(/requireStep\(\s*(?:'|"|`)(?:[^'"`]|\\.)*(?:'|"|`)\s*,\s*'([a-z-]+)'\s*,\s*(null|'[A-Za-z0-9_-]+')/g)) {
      if (!tabs.has(m[1])) badJumps.push('tab:' + m[1]);
      if (m[2] !== 'null' && !ids.has(m[2].replace(/'/g, ''))) badJumps.push('card:' + m[2]);
    }
    checks.push({ ok: badJumps.length === 0, msg: `every jump target resolves (${list(badJumps)})` });

    // 5. Shipped files: everything the service worker precaches, and every asset the shell and
    //    manifest reference, must exist — a missing entry fails the SW install silently.
    const sw = read('sw.js');
    const preBlock = sw.slice(sw.indexOf('const PRECACHE'), sw.indexOf(']', sw.indexOf('const PRECACHE')));
    const missingPrecache = [...preBlock.matchAll(/'\.\/([^']+)'/g)]
      .map(m => m[1]).filter(p => p && !fs.existsSync(path.join(ROOT, p)));
    const manifest = JSON.parse(read('manifest.json'));
    const missingIcons = (manifest.icons || []).map(i => i.src)
      .filter(a => !fs.existsSync(path.join(ROOT, a.replace(/^\.\//, ''))));
    const missingAssets = [...html.matchAll(/(?:href|src)="(?!http|data:|#)([^"]+)"/g)]
      .map(m => m[1]).filter(a => !fs.existsSync(path.join(ROOT, a)));
    const missingFiles = [...missingPrecache, ...missingIcons, ...missingAssets];
    checks.push({ ok: missingFiles.length === 0, msg: `every shipped asset exists on disk (${list(missingFiles)})` });

    // 6. querySelector('#id') targets must exist in the shell or be generated by JS.
    const badQs = [...js.matchAll(/querySelector\(\s*'#([A-Za-z0-9_-]+)'/g)]
      .map(m => m[1])
      .filter(q => !ids.has(q) && !new RegExp(`id="${q}"|id = '${q}'`).test(js));
    checks.push({ ok: badQs.length === 0, msg: `every querySelector #id target exists (${list(badQs)})` });

    // 7. The two shells must stay byte-identical — index.html is the deployed mirror.
    checks.push({ ok: read('character-tracker.html') === read('index.html'),
                  msg: 'character-tracker.html and index.html are identical' });

    return { checks };
  }
};
